/**
 * Copyright (C) Derek Sunder
 *  ____                _      ____                  _
 * |  _ \  ___ _ __ ___| | __ / ___| _   _ _ __   __| | ___ _ __
 * | | | |/ _ \ '__/ _ \ |/ / \___ \| | | | '_ \ / _` |/ _ \ '__|
 * | |_| |  __/ | |  __/   <   ___) | |_| | | | | (_| |  __/ |
 * |____/ \___|_|  \___|_|\_\ |____/ \__,_|_| |_|\__,_|\___|_|
 */

/* liburing header for PHP */

#ifndef _PHP_CURL_H
#define _PHP_CURL_H

#include <liburing.h>
#include "php.h"

static void add_liburing_constants(int module_number)
{
	REGISTER_LONG_CONSTANT("IO_TYPE_DISK", 1, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IO_TYPE_SOCKET", 2, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IOSQE_FIXED_FILE", IOSQE_FIXED_FILE, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IOSQE_IO_DRAIN", IOSQE_IO_DRAIN, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IOSQE_IO_LINK", IOSQE_IO_LINK, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IOSQE_IO_HARDLINK", IOSQE_IO_HARDLINK, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IOSQE_ASYNC", IOSQE_ASYNC, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IOSQE_BUFFER_SELECT", IOSQE_BUFFER_SELECT, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IOSQE_CQE_SKIP_SUCCESS", IOSQE_CQE_SKIP_SUCCESS, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_IOPOLL", IORING_SETUP_IOPOLL, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_SQPOLL", IORING_SETUP_SQPOLL, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_SQ_AFF", IORING_SETUP_SQ_AFF, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_CQSIZE", IORING_SETUP_CQSIZE, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_CLAMP", IORING_SETUP_CLAMP, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_ATTACH_WQ", IORING_SETUP_ATTACH_WQ, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_R_DISABLED", IORING_SETUP_R_DISABLED, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_SUBMIT_ALL", IORING_SETUP_SUBMIT_ALL, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_COOP_TASKRUN", IORING_SETUP_COOP_TASKRUN, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_TASKRUN_FLAG", IORING_SETUP_TASKRUN_FLAG, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_SQE128", IORING_SETUP_SQE128, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_CQE32", IORING_SETUP_CQE32, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_SINGLE_ISSUER", IORING_SETUP_SINGLE_ISSUER, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_DEFER_TASKRUN", IORING_SETUP_DEFER_TASKRUN, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_NO_MMAP", IORING_SETUP_NO_MMAP, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_REGISTERED_FD_ONLY", IORING_SETUP_REGISTERED_FD_ONLY, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SETUP_NO_SQARRAY", IORING_SETUP_NO_SQARRAY, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_URING_CMD_FIXED", IORING_URING_CMD_FIXED, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FSYNC_DATASYNC", IORING_FSYNC_DATASYNC, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_TIMEOUT_ABS", IORING_TIMEOUT_ABS, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_TIMEOUT_UPDATE", IORING_TIMEOUT_UPDATE, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_TIMEOUT_BOOTTIME", IORING_TIMEOUT_BOOTTIME, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_TIMEOUT_REALTIME", IORING_TIMEOUT_REALTIME, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_LINK_TIMEOUT_UPDATE", IORING_LINK_TIMEOUT_UPDATE, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_TIMEOUT_ETIME_SUCCESS", IORING_TIMEOUT_ETIME_SUCCESS, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_TIMEOUT_MULTISHOT", IORING_TIMEOUT_MULTISHOT, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_TIMEOUT_CLOCK_MASK", IORING_TIMEOUT_CLOCK_MASK, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_TIMEOUT_UPDATE_MASK", IORING_TIMEOUT_UPDATE_MASK, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("SPLICE_F_FD_IN_FIXED", SPLICE_F_FD_IN_FIXED, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_POLL_ADD_MULTI", IORING_POLL_ADD_MULTI, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_POLL_UPDATE_EVENTS", IORING_POLL_UPDATE_EVENTS, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_POLL_UPDATE_USER_DATA", IORING_POLL_UPDATE_USER_DATA, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_POLL_ADD_LEVEL", IORING_POLL_ADD_LEVEL, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_ASYNC_CANCEL_ALL", IORING_ASYNC_CANCEL_ALL, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_ASYNC_CANCEL_FD", IORING_ASYNC_CANCEL_FD, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_ASYNC_CANCEL_ANY", IORING_ASYNC_CANCEL_ANY, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_ASYNC_CANCEL_FD_FIXED", IORING_ASYNC_CANCEL_FD_FIXED, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_RECVSEND_POLL_FIRST", IORING_RECVSEND_POLL_FIRST, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_RECV_MULTISHOT", IORING_RECV_MULTISHOT, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_RECVSEND_FIXED_BUF", IORING_RECVSEND_FIXED_BUF, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SEND_ZC_REPORT_USAGE", IORING_SEND_ZC_REPORT_USAGE, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_NOTIF_USAGE_ZC_COPIED", IORING_NOTIF_USAGE_ZC_COPIED, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_ACCEPT_MULTISHOT", IORING_ACCEPT_MULTISHOT, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_MSG_RING_CQE_SKIP", IORING_MSG_RING_CQE_SKIP, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_MSG_RING_FLAGS_PASS", IORING_MSG_RING_FLAGS_PASS, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FIXED_FD_NO_CLOEXEC", IORING_FIXED_FD_NO_CLOEXEC, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_CQE_F_BUFFER", IORING_CQE_F_BUFFER, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_CQE_F_MORE", IORING_CQE_F_MORE, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_CQE_F_SOCK_NONEMPTY", IORING_CQE_F_SOCK_NONEMPTY, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_CQE_F_NOTIF", IORING_CQE_F_NOTIF, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_OFF_SQ_RING", IORING_OFF_SQ_RING, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_OFF_CQ_RING", IORING_OFF_CQ_RING, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_OFF_SQES", IORING_OFF_SQES, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_OFF_PBUF_RING", IORING_OFF_PBUF_RING, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_OFF_PBUF_SHIFT", IORING_OFF_PBUF_SHIFT, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_OFF_MMAP_MASK", IORING_OFF_MMAP_MASK, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SQ_NEED_WAKEUP", IORING_SQ_NEED_WAKEUP, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SQ_CQ_OVERFLOW", IORING_SQ_CQ_OVERFLOW, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_SQ_TASKRUN", IORING_SQ_TASKRUN, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_CQ_EVENTFD_DISABLED", IORING_CQ_EVENTFD_DISABLED, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_ENTER_GETEVENTS", IORING_ENTER_GETEVENTS, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_ENTER_SQ_WAKEUP", IORING_ENTER_SQ_WAKEUP, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_ENTER_SQ_WAIT", IORING_ENTER_SQ_WAIT, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_ENTER_EXT_ARG", IORING_ENTER_EXT_ARG, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_ENTER_REGISTERED_RING", IORING_ENTER_REGISTERED_RING, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_SINGLE_MMAP", IORING_FEAT_SINGLE_MMAP, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_NODROP", IORING_FEAT_NODROP, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_SUBMIT_STABLE", IORING_FEAT_SUBMIT_STABLE, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_RW_CUR_POS", IORING_FEAT_RW_CUR_POS, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_CUR_PERSONALITY", IORING_FEAT_CUR_PERSONALITY, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_FAST_POLL", IORING_FEAT_FAST_POLL, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_POLL_32BITS", IORING_FEAT_POLL_32BITS, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_SQPOLL_NONFIXED", IORING_FEAT_SQPOLL_NONFIXED, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_EXT_ARG", IORING_FEAT_EXT_ARG, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_NATIVE_WORKERS", IORING_FEAT_NATIVE_WORKERS, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_RSRC_TAGS", IORING_FEAT_RSRC_TAGS, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_CQE_SKIP", IORING_FEAT_CQE_SKIP, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_LINKED_FILE", IORING_FEAT_LINKED_FILE, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_FEAT_REG_REG_RING", IORING_FEAT_REG_REG_RING, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_RSRC_REGISTER_SPARSE", IORING_RSRC_REGISTER_SPARSE, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IORING_REGISTER_FILES_SKIP", IORING_REGISTER_FILES_SKIP, CONST_PERSISTENT | CONST_CS);
	REGISTER_LONG_CONSTANT("IO_URING_OP_SUPPORTED", IO_URING_OP_SUPPORTED, CONST_PERSISTENT | CONST_CS);
}

#endif  /* _PHP_CURL_H */
